version: "3.9"
services:
  web:
    build: .
    volumes:
      # this will be our container volume
      - .:/home/jovyan/repo
    environment:
      # launch jupyter in the lab env
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
    ports:
      # bind port 8888 to containers port 8888
      - "8888:8888"
